config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "iad-taoxie1025.c9users.io" #After you pull from the repository, change this to your cloud9 address

  resource :users
  resources :posts,          only: [:create, :destroy, :update]
  resource :feedbacks
  
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  root 'welcome#home'
  get 'welcome/about', to: 'welcome#about'
  
  get 'users/new', to: 'users#new'
  post 'users/' => 'users#show', :as => 'user'
  get 'users/set_as_admin', to: 'users#set_as_admin'
  get 'users/set_as_user', to: 'users#set_as_user'
  get 'users/delete_user', to: 'users#delete_user'
  patch 'users/update_by_admin', to: 'users#update_by_admin'

  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get 'posts/new', to: 'posts#new'
  get 'posts/edit', to: 'posts#edit'
  get 'posts/show', to: 'posts#show'
  get 'posts/update', to: 'posts#update'
  
  get 'welcome/home', to: 'welcome#home'
  get 'welcome/show', to: 'welcome#show'
  get 'welcome/search', to: 'welcome#search'

  post 'feedback/create', to: 'feedback#create'
  get 'feedback/new', to: 'feedback#new'
  get 'search', to: 'welcome#search'
  
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  
  get 'admin/show', to: 'admin#show'
  get 'admin/show_all_posts', to: 'admin#show_all_posts'

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    
    before_action :authenticate_with_http_digest
    
    def new
        @receiptient = User.where(id: params[:receiptientID])
        @subject = params[:subject]
    end
    
    def create
        recipients = User.where(id: conversation_params[:recipients])
        if (conversation_params[:body].present? && conversation_params[:subject].present?)
            conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
            flash[:success] = "Your message was successfully sent!"
            redirect_to conversation_path(conversation)
        else
            flash[:danger] = "Message failed to sent!"
            redirect_to :controller => 'conversations', :action => 'new'
        end

    end

    def show
        @receipts = conversation.receipts_for(current_user)
        # mark conversation as read
        conversation.mark_as_read(current_user)
    end
    
     def reply
        current_user.reply_to_conversation(conversation, message_params[:body])
        if (message_params[:body].present?)
            flash[:success] = "Your reply message was successfully sent!"
            redirect_to conversation_path(conversation)
         else
            flash[:danger] = "Message failed to sent!"
            redirect_to :controller => 'conversations', :action => 'show'
        end
     end
     
      def trash
        conversation.move_to_trash(current_user)
        redirect_to mailbox_inbox_path
      end
    
      def untrash
        conversation.untrash(current_user)
        redirect_to mailbox_inbox_path
      end
    
    
    private

    def conversation_params
        params.require(:conversation).permit(:subject, :body, recipients:[])
    end
      
    def message_params
        params.require(:message).permit(:body, :subject)
    end
    
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <% if current_user.id == conversation.originator %>
      <%= image_tag "#{conversation.originator.image.url(:medium)}", :size => '90x90' %>
    <% else %>
      <%= image_tag "#{conversation.recipients.first.image.url(:medium)}", :size => '90x90' %>
    <% end %>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.recipients.first.name %> <br>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <%= truncate conversation.messages.last.body, length: 145 %>
    <%= link_to "View", conversation_path(conversation)  %>
  </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <%= f.label :recipients %>
      <% if @receiptient.present? %>
        <%= f.select(:recipients, @receiptient.all.collect {|p| [ p.name, p.id ] }, {}, { multiple: true , class: "chosen-select form-control" })%>
      <% else %>
        <%= f.text_field :receiptient, placeholder: "Enter recipients", class: "form-control" %>
      <% end %>
    </div>
      
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, :value => @subject.to_s, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>

    <%= f.submit "Send Message", class: "btn btn-success" %>

<% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
          <%= image_tag "#{message.sender.image.url(:medium)}", :size => '90x90' %>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.name %> <br>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <%= message.body %>
      </div>
    </div>
<% end %>

app/views/conversations/new.html.erb
<br><br><br>

<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<br><br><br>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<div id='conversations_show'>
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-6">
    <%= link_to "Compose", new_conversation_path, class: "btn btn-success" %>
  </div>
  <br>
  <div class="col-md-6 text-right">
    <% if conversation.is_trashed?(current_user) %>
        <%= link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
    <% else %>
        <%= link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn btn-danger', method: :post,
                    data: {confirm: 'Are you sure?'} %> 
    <% end %>
  </div>
</div>

<div class="row">
  <div class="spacer"></div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
      <div class="panel-footer">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>
            <%= f.submit "Reply", class: 'btn btn-danger pull-right' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>
</div>