config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "iad-taoxie1025.c9users.io" #After you pull from the repository, change this to your cloud9 address

  resource :users
  resources :posts,          only: [:create, :destroy, :update]
  resource :feedbacks
  
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  root 'welcome#home'
  get 'welcome/about', to: 'welcome#about'
  
  get 'users/new', to: 'users#new'
  post 'users/' => 'users#show', :as => 'user'
  get 'users/set_as_admin', to: 'users#set_as_admin'
  get 'users/set_as_user', to: 'users#set_as_user'
  get 'users/delete_user', to: 'users#delete_user'
  patch 'users/update_by_admin', to: 'users#update_by_admin'

  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get 'posts/new', to: 'posts#new'
  get 'posts/edit', to: 'posts#edit'
  get 'posts/show', to: 'posts#show'
  get 'posts/update', to: 'posts#update'
  
  get 'welcome/home', to: 'welcome#home'
  get 'welcome/show', to: 'welcome#show'
  get 'welcome/search', to: 'welcome#search'

  post 'feedback/create', to: 'feedback#create'
  get 'feedback/new', to: 'feedback#new'
  get 'search', to: 'welcome#search'
  
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  
  get 'admin/show', to: 'admin#show'
  get 'admin/show_all_posts', to: 'admin#show_all_posts'

end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
    
    before_action :authenticate_with_http_digest

    def inbox
        @inbox = mailbox.inbox
        @active = :inbox
    end
    
    def sent
        @sent = mailbox.sentbox
        @active = :sent
    end
    
    def trash
        @trash = mailbox.trash
        @active = :trash
    end

    
end

app/helpers/mailbox_helper.rb
module MailboxHelper
    
    def unread_messages_count
        # how to get the number of unread messages for the current user
        # using mailboxer
        mailbox.inbox(:unread => true).count(:id, :distinct => true)
    end
      
end

app/views/mailbox/_folder_view.html.erb
<div id='folder_view' class="row">
  <div class="spacer"></div>
  <div class="col-md-12">
    <%= link_to "Compose", new_conversation_path, class: "btn btn-success" %>
    <div class="spacer"></div>
    <br>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <% if is_conversation %>
            <%= render 'conversations/form' %>
        <% else %>
          <%= render partial: 'conversations/conversation', collection: messages %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/mailbox/_folders.html.erb
<ul class="nav nav-pills nav-stacked">
  <li class="<%= active_page(:inbox) %>">
    <%= link_to mailbox_inbox_path do  %>
        <span class="label label-danger pull-right"><%=unread_messages_count%></span>
        <em class="fa fa-inbox fa-lg"></em>
        <span>Inbox</span>
    <% end %>
  </li>
  <li class="<%= active_page(:sent) %>">
    <%= link_to mailbox_sent_path do %>

        <em class="fa fa-paper-plane-o fa-lg"></em>
        <span>Sent</span>
    <% end %>
  </li>

  <li class="<%= active_page(:trash) %>">
    <%= link_to mailbox_trash_path do %>
        <em class="fa fa-trash-o fa-lg"></em>
        <span>Trash</span>
    <% end %>
  </li>
</ul>

app/views/mailbox/inbox.html.erb
<br><br><br>
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @inbox } %>

app/views/mailbox/sent.html.erb
<br><br><br>
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @sent } %>

app/views/mailbox/trash.html.erb
<br><br><br>
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @trash } %>