config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "iad-taoxie1025.c9users.io" #After you pull from the repository, change this to your cloud9 address

  resource :users
  resources :posts,          only: [:create, :destroy, :update]
  resource :feedbacks
  
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  root 'welcome#home'
  get 'welcome/about', to: 'welcome#about'
  
  get 'users/new', to: 'users#new'
  post 'users/' => 'users#show', :as => 'user'
  get 'users/set_as_admin', to: 'users#set_as_admin'
  get 'users/set_as_user', to: 'users#set_as_user'
  get 'users/delete_user', to: 'users#delete_user'
  patch 'users/update_by_admin', to: 'users#update_by_admin'

  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get 'posts/new', to: 'posts#new'
  get 'posts/edit', to: 'posts#edit'
  get 'posts/show', to: 'posts#show'
  get 'posts/update', to: 'posts#update'
  
  get 'welcome/home', to: 'welcome#home'
  get 'welcome/show', to: 'welcome#show'
  get 'welcome/search', to: 'welcome#search'

  post 'feedback/create', to: 'feedback#create'
  get 'feedback/new', to: 'feedback#new'
  get 'search', to: 'welcome#search'
  
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  
  get 'admin/show', to: 'admin#show'
  get 'admin/show_all_posts', to: 'admin#show_all_posts'

end

app/models/post.rb
class Post < ActiveRecord::Base
    
    belongs_to :user
    
    has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#" }
     validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
     
    default_scope -> { order(created_at: :desc) }
    validates :user_id, presence: true
    validates :courseName, presence: true
    validates :courseCode, presence: true
    validates :department, presence: true
    validates :description, presence: true, length: { maximum: 500 }
    
    def self.search(search)
     if search
      where("courseName LIKE ? OR courseCode LIKE ? OR department LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
     else
      scoped
     end
    end
    
    def self.findBy(postId)
     Post.find_by id: "#{postId}"
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    before_action :logged_in_user, only: [:create, :destroy]
    
    def new
        @post = Post.new
    end

    def create
        @post = current_user.posts.build(post_params)
        if @post.save
            flash[:success] = "You Ad is created!"
            redirect_to :controller => 'posts', :action => 'show', :id => @post.id
        else
            render 'new'
        end
    end
    
    def destroy
    end
    
    def show
        @feedback = Feedback.new
    end
    
    def edit
        @post = Post.find(params[:post_id])
    end
    
    def update
        @post = Post.find(params[:id])
        if @post.update_attributes(post_params)
            flash[:success] = "You changes were saved successfully"
            redirect_to :controller => 'posts', :action => 'show', :id => @post.id
         else
            render 'edit'
        end
    end
    
    def destroy
        Post.find(params[:id]).destroy
        flash[:success] = "Post deleted"
        if current_user.isAdmin
            redirect_to(:back)
        else
            redirect_to users_url
        end
    end
    
    private

    def post_params
      params.require(:post).permit(:courseName, :courseCode, :price, :department, :description)
    end
    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<li id="post-<%= post.id%>">
  <div>
    <h2>
      <%= link_to image_tag(User.find(post.user_id).image.url(:medium), :size => '55x50'), :controller => "posts", :action => :show, :post => post.id%>
      <%= link_to post.courseName + " " + post.courseCode, :controller => "posts", :action => :show, :post => post.id %>
      </h2>
    <ul>
        <li>Posted <%= time_ago_in_words(post.created_at) unless post.created_at.blank? %> ago.
            <% if  (current_user.present? && current_user.id == post.user_id) || (current_user.present? &&current_user.isAdmin) %>
              <%= link_to "Edit", posts_edit_path(post_id: post.id), class: "btn-xs btn-primary" %>
              <%= link_to "Delete", post, method: :delete, class: "btn-xs btn-danger", data: { confirm: "You sure?" } %>
              <% end %>
        </li>
    </ul>
  </div>
</li>

app/views/posts/edit.html.erb
<br><br><br>

<% if logged_in? %>
<div class="container">
  <div class="row">
    <aside class="col-xs-6">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="post_form">
        <%= render 'shared/post_edit_form' %>
      </section>
    </aside>
  
<% end %>

app/views/posts/new.html.erb
<br><br><br>
<% if logged_in? %>
<div class="container">
  <div class="row">
    <aside class="col-xs-6">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="post_form">
        <%= render 'shared/post_form' %>
      </section>
    </aside>
  
<% end %>

    <div class="col-xs-6">
      <% if current_user.posts.any? %>
        <h3>Posts (<%= current_user.posts.count %>)</h3>
        <ol class="microposts">
            <%= render current_user.posts %>
        </ol>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<br><br><br>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>


<div id='post_show'>
    <% if params[:post] %>
        <% @post = Post.find(params[:post]) %>
    <% elsif params[:id]%>
        <% @post = Post.findBy(params[:id]) %>
    <% end %>

   
<div class="row">
    <aside class="col-md-4">
        <br>
         <%= image_tag User.find(@post.user_id).image.url(:medium) %>
         <br><br>
        <div style="width:155px;">
        <% receiptientID = @post.user_id %>
        <% subject = "Inquiry about \"" + @post.courseName + " " + @post.courseCode + "\"" %>
        <%= link_to "Send message to me", { :controller => "conversations", 
            :action => "new", 
            :receiptientID => receiptientID, 
            :subject => subject},
            class: "btn btn-primary" %>
        </div>
    </aside>
    <h2><%= @post.courseName %></h2>
    <h6><%= @post.courseCode %>, <%= @post.department %>, $<%= @post.price %> per hour
        - Posted by <%= User.find(@post.user_id).name %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <% if current_user.present? && current_user.id == @post.user_id %>
              <%= link_to "Edit", posts_edit_path(post_id: @post.id), class: "btn-xs btn-primary" %>
              <%= link_to "Delete", @post, method: :delete, class: "btn-xs btn-danger", data: { confirm: "You sure?" } %>
              <% end %>
    </h6>


    <div class="col-md-8">
    <hr>
    <p><%= @post.description %></p>
    <% if logged_in? %>

    <% end %>
    <br><br>
    <h2>Comments</h2>
    <% @feedbacks = Feedback.search(@post.id) %>
    <% @feedbacks.each do |feedback| %>
        <%= render 'shared/comment', :feedback => feedback %>
    <% end %>
    
    <%= render 'shared/write_comments' %>
     </aside>
</div>
</div>