config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "iad-taoxie1025.c9users.io" #After you pull from the repository, change this to your cloud9 address

  resource :users
  resources :posts,          only: [:create, :destroy, :update]
  resource :feedbacks
  
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  root 'welcome#home'
  get 'welcome/about', to: 'welcome#about'
  
  get 'users/new', to: 'users#new'
  post 'users/' => 'users#show', :as => 'user'
  get 'users/set_as_admin', to: 'users#set_as_admin'
  get 'users/set_as_user', to: 'users#set_as_user'
  get 'users/delete_user', to: 'users#delete_user'
  patch 'users/update_by_admin', to: 'users#update_by_admin'

  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get 'posts/new', to: 'posts#new'
  get 'posts/edit', to: 'posts#edit'
  get 'posts/show', to: 'posts#show'
  get 'posts/update', to: 'posts#update'
  
  get 'welcome/home', to: 'welcome#home'
  get 'welcome/show', to: 'welcome#show'
  get 'welcome/search', to: 'welcome#search'

  post 'feedback/create', to: 'feedback#create'
  get 'feedback/new', to: 'feedback#new'
  get 'search', to: 'welcome#search'
  
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  
  get 'admin/show', to: 'admin#show'
  get 'admin/show_all_posts', to: 'admin#show_all_posts'

end

app/views/layouts/_navigation_bar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "@Tutor", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", :controller => :welcome, :action => :about %></li>
        <% if logged_in? %>
          <li><%= link_to "Post Your Ad", :controller => :posts, :action => :new %></li>
          <% if unread_messages_count == 0%>
            <li><%= link_to "Inbox", mailbox_inbox_path %></li>
          <% else %>
            <li><%= link_to "Inbox".html_safe, mailbox_inbox_path %></li>
            <li><%= link_to "#{image_tag("mail_new_icon", :size => '25x22')}".html_safe, mailbox_inbox_path, :class => "blink-image" %></li>
          <% end %>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <% if current_user.isAdmin %>
                <li><%= link_to "Administrator Entry", {:controller => "admin", :action => "show"} %></li>
              <% end %>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", :controller => :users, :action => :new %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigation_bar' %>
<%= yield %>

</body>
</html>